-- Encuentra pedidos entregados tarde y calcula los días de retraso
SELECT 
    O.ORDER_ID,
    C.CUSTOMER_CITY AS ciudad_destino,
    C.CUSTOMER_STATE AS estado_destino,
    O.ESTIMATED_DELIVERY_DATE AS fecha_promesa,
    O.DELIVERED_CUSTOMER_TIMESTAMP AS fecha_entrega_real,
    EXTRACT(DAY FROM (O.DELIVERED_CUSTOMER_TIMESTAMP - O.ESTIMATED_DELIVERY_DATE::TIMESTAMP)) AS dias_retraso
FROM ORDERS O
JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE O.ORDER_STATUS = 'delivered'
  AND O.DELIVERED_CUSTOMER_TIMESTAMP > O.ESTIMATED_DELIVERY_DATE::TIMESTAMP
ORDER BY dias_retraso DESC;