CREATE TABLE CUSTOMERS (
	CUSTOMER_ID UUID PRIMARY KEY,
	CUSTOMER_UNIQUE_ID TEXT UNIQUE NOT NULL,
	CUSTOMER_ZIP_CODE_PREFIX TEXT,
	CUSTOMER_CITY TEXT,
	CUSTOMER_STATE TEXT,
	CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);