-- ==========================================
-- 1. ELIMINAR TABLAS (OPCIONAL)
-- (El orden es inverso a la creación para 
-- no violar las claves foráneas al borrarlas)
-- ==========================================
DROP TABLE IF EXISTS REVIEWS;
DROP TABLE IF EXISTS PAYMENTS;
DROP TABLE IF EXISTS ORDER_ITEMS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS CUSTOMERS;

USE ECOMMIFY;

-- ==========================================
-- 2. CREACIÓN DE TABLAS MAESTRAS (Sin dependencias)
-- ==========================================

CREATE TABLE CUSTOMERS (
	CUSTOMER_ID UUID PRIMARY KEY,
	CUSTOMER_UNIQUE_ID TEXT UNIQUE NOT NULL,
	CUSTOMER_ZIP_CODE_PREFIX TEXT,
	CUSTOMER_CITY TEXT,
	CUSTOMER_STATE TEXT,
	CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE PRODUCTS (
	PRODUCT_ID UUID PRIMARY KEY,
	PRODUCT_CATEGORY_NAME TEXT,
	PRODUCT_NAME_LENGTH INT,
	PRODUCT_DESCRIPTION_LENGTH INT,
	PRODUCT_PHOTOS_QTY INT,
	PRODUCT_WEIGHT_G INT,
	PRODUCT_LENGTH_CM INT,
	PRODUCT_HEIGHT_CM INT,
	PRODUCT_WIDTH_CM INT,
	ATTRIBUTES JSONB
);

-- ==========================================
-- 3. CREACIÓN DE TABLAS TRANSACCIONALES
-- ==========================================

-- Depende de: CUSTOMERS
CREATE TABLE ORDERS (
	ORDER_ID UUID PRIMARY KEY,
	CUSTOMER_ID UUID NOT NULL REFERENCES CUSTOMERS (CUSTOMER_ID),
	ORDER_STATUS TEXT NOT NULL,
	PURCHASE_TIMESTAMP TIMESTAMPTZ NOT NULL,
	APPROVED_TIMESTAMP TIMESTAMPTZ,
	DELIVERED_CARRIER_TIMESTAMP TIMESTAMPTZ,
	DELIVERED_CUSTOMER_TIMESTAMP TIMESTAMPTZ,
	ESTIMATED_DELIVERY_DATE DATE
);

-- Depende de: ORDERS y PRODUCTS
CREATE TABLE ORDER_ITEMS (
	ORDER_ITEM_ID UUID PRIMARY KEY,
	ORDER_ID UUID NOT NULL REFERENCES ORDERS (ORDER_ID),
	PRODUCT_ID UUID NOT NULL REFERENCES PRODUCTS (PRODUCT_ID),
	SELLER_ID UUID NOT NULL,
	PRICE NUMERIC(12, 2) NOT NULL CHECK (PRICE >= 0),
	FREIGHT_VALUE NUMERIC(12, 2) NOT NULL CHECK (FREIGHT_VALUE >= 0),
	ATTRIBUTES_SNAPSHOT JSONB
);

-- Depende de: ORDERS
CREATE TABLE PAYMENTS (
	PAYMENT_ID UUID PRIMARY KEY,
	ORDER_ID UUID NOT NULL REFERENCES ORDERS (ORDER_ID),
	PAYMENT_SEQUENTIAL INT NOT NULL,
	PAYMENT_TYPE TEXT NOT NULL,
	PAYMENT_INSTALLMENTS INT NOT NULL CHECK (PAYMENT_INSTALLMENTS > 0),
	PAYMENT_VALUE NUMERIC(12, 2) NOT NULL CHECK (PAYMENT_VALUE >= 0)
);

-- Depende de: ORDERS
CREATE TABLE REVIEWS (
	REVIEW_ID UUID PRIMARY KEY,
	ORDER_ID UUID NOT NULL REFERENCES ORDERS (ORDER_ID),
	REVIEW_SCORE INT NOT NULL CHECK (REVIEW_SCORE BETWEEN 1 AND 5),
	REVIEW_COMMENT_TITLE TEXT,
	REVIEW_COMMENT_MESSAGE TEXT,
	REVIEW_CREATION_DATE TIMESTAMPTZ,
	REVIEW_ANSWER_TIMESTAMP TIMESTAMPTZ
);