CREATE TABLE ORDERS (
	ORDER_ID UUID PRIMARY KEY,
	CUSTOMER_ID UUID NOT NULL REFERENCES CUSTOMERS (CUSTOMER_ID),
	ORDER_STATUS TEXT NOT NULL,
	PURCHASE_TIMESTAMP TIMESTAMPTZ NOT NULL,
	APPROVED_TIMESTAMP TIMESTAMPTZ,
	DELIVERED_CARRIER_TIMESTAMP TIMESTAMPTZ,
	DELIVERED_CUSTOMER_TIMESTAMP TIMESTAMPTZ,
	ESTIMATED_DELIVERY_DATE DATE
);