CREATE TABLE ORDER_ITEMS (
	ORDER_ITEM_ID UUID PRIMARY KEY,
	ORDER_ID UUID NOT NULL REFERENCES ORDERS (ORDER_ID),
	PRODUCT_ID UUID NOT NULL REFERENCES PRODUCTS (PRODUCT_ID),
	SELLER_ID UUID NOT NULL,
	PRICE NUMERIC(12, 2) NOT NULL CHECK (PRICE >= 0),
	FREIGHT_VALUE NUMERIC(12, 2) NOT NULL CHECK (FREIGHT_VALUE >= 0),
	ATTRIBUTES_SNAPSHOT JSONB
);