CREATE TABLE PAYMENTS (
	PAYMENT_ID UUID PRIMARY KEY,
	ORDER_ID UUID NOT NULL REFERENCES ORDERS (ORDER_ID),
	PAYMENT_SEQUENTIAL INT NOT NULL,
	PAYMENT_TYPE TEXT NOT NULL,
	PAYMENT_INSTALLMENTS INT NOT NULL CHECK (PAYMENT_INSTALLMENTS > 0),
	PAYMENT_VALUE NUMERIC(12, 2) NOT NULL CHECK (PAYMENT_VALUE >= 0)
);