CREATE TABLE PRODUCTS (
	PRODUCT_ID UUID PRIMARY KEY,
	PRODUCT_CATEGORY_NAME TEXT,
	PRODUCT_NAME_LENGTH INT,
	PRODUCT_DESCRIPTION_LENGTH INT,
	PRODUCT_PHOTOS_QTY INT,
	PRODUCT_WEIGHT_G INT,
	PRODUCT_LENGTH_CM INT,
	PRODUCT_HEIGHT_CM INT,
	PRODUCT_WIDTH_CM INT,
	ATTRIBUTES JSONB
);