CREATE TABLE REVIEWS (
	REVIEW_ID UUID PRIMARY KEY,
	ORDER_ID UUID NOT NULL REFERENCES ORDERS (ORDER_ID),
	REVIEW_SCORE INT NOT NULL CHECK (REVIEW_SCORE BETWEEN 1 AND 5),
	REVIEW_COMMENT_TITLE TEXT,
	REVIEW_COMMENT_MESSAGE TEXT,
	REVIEW_CREATION_DATE TIMESTAMPTZ,
	REVIEW_ANSWER_TIMESTAMP TIMESTAMPTZ
);